jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    
    encoders:
        MA\UserBundle\Entity\User: sha512   #plaintext pour aucun encodage
        # Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        # ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]       # Un admin hérite des droits d'auteur et de modérateur
        # ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] # On garde ce rôle superadmin, il nous resservira par la suite

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username_email

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /%locale%/admin
            logout:
                path:       fos_user_security_logout
                target:     /%locale%/
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/fr/user/, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/en/user/, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/user/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }
        - { path: ^/fr/user/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }
        - { path: ^/en/user/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }
